"""Global helpers for Heiwa."""

__all__ = [
	"STATUS_BAD_REQUEST",
	"STATUS_CREATED",
	"STATUS_FORBIDDEN",
	"STATUS_INTERNAL_SERVER_ERROR",
	"STATUS_NO_CONTENT",
	"STATUS_NOT_FOUND",
	"STATUS_OK",
	"STATUS_UNAUTHORIZED"
]
__version__ = "1.0.0"

STATUS_CREATED = 201
STATUS_NO_CONTENT = 204
STATUS_OK = 200

STATUS_BAD_REQUEST = 400
STATUS_UNAUTHORIZED = 401
STATUS_FORBIDDEN = 403
STATUS_NOT_FOUND = 404

STATUS_INTERNAL_SERVER_ERROR = 500
